# Site settings
title: Decoding Gender in Fictional Character Development
tag_text: Decoding Gender in Fictional Character Development
description: A responsive template for publishing single-page websites, articles that are easy on the eyes
url: "https://decoding-gender.github.io" # base URL for your site ie. "https://www.example.com"
baseurl: # subpath for base of site, leave blank if hosting at root

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
